# Generated by Django 5.0.2 on 2024-12-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auc', '0001_initial'),
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionsPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.BooleanField(default=False, verbose_name='permission')),
                ('auctions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auc.auctionmodel', verbose_name='auctions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Auction access',
                'verbose_name_plural': 'accesses',
            },
        ),
    ]
