# Generated by Django 5.0.2 on 2024-12-25 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='data/auction_images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='AuctionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('starting_price', models.FloatField(verbose_name='starting price')),
                ('current_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='current price')),
                ('increment_step', models.FloatField(default=50000, verbose_name='increment step')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('images', models.ManyToManyField(blank=True, related_name='auctions', to='auc.auctionimage', verbose_name='images')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_auctions', to=settings.AUTH_USER_MODEL, verbose_name='winner')),
            ],
            options={
                'verbose_name': 'auction',
                'verbose_name_plural': 'auctions',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='bid amount')),
                ('bid_time', models.DateTimeField(auto_now_add=True, verbose_name='bid time')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auc.auctionmodel', verbose_name='auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='bidder')),
            ],
            options={
                'verbose_name': 'bid',
                'verbose_name_plural': 'bids',
            },
        ),
        migrations.AddField(
            model_name='auctionmodel',
            name='bidders',
            field=models.ManyToManyField(related_name='bids', through='auc.Bid', to=settings.AUTH_USER_MODEL, verbose_name='bidders'),
        ),
    ]
