# Generated by Django 5.0.2 on 2024-12-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionmodel',
            name='current_price',
            field=models.FloatField(default=0.0, verbose_name='current price'),
        ),
    ]
