# Generated by Django 5.0.2 on 2024-12-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auc', '0002_alter_auctionmodel_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
